name: Compilar APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Crear estructura Android respetando codigo
        run: |
          mkdir -p .backup
          cp -r lib/* .backup/ 2>/dev/null || true
          flutter create --platforms=android .
          rm -rf lib/*
          cp -r .backup/* lib/ 2>/dev/null || true
          rm -rf .backup

      - name: Instalar dependencias
        run: flutter pub get

      - name: Generar icono personalizado
        run: |
          if [ -f "app_icon.png" ]; then
            dart run flutter_launcher_icons
          fi

      - name: Compilar APK
        run: flutter build apk --release --no-tree-shake-icons

      - name: Subir instalador APK
        uses: actions/upload-artifact@v4
        with:
          name: pseudocode-pro-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          
